In [ ]:
# https://fivethirtyeight.com/features/can-you-find-the-luckiest-coin/

import numpy as np
from scipy.stats import binom

# There are two absorbing states: when there is 1 coin left (winning with a lucky coin) or 0 coins left (losing)
# We want to construct a transition matrix of each number of coins left to each possible number of coins remaining after flipping
# We can find the exact probabilities using the binomial distribution, and fill out a matrix of transition probability
# We use N=1000 because a 1,000,000  ^ 2 cell transition matrix is too large

max_n = 1000
m = np.zeros((max_n+1,max_n+1))
p = 0.5
for n in range(1,max_n+1):
    for k in range(0,n+1):
        m[max_n-n,max_n-k] = binom.pmf(k, n, p, loc=0)
        
# Modify the probability of transition to 0 for absorbing state (1 coin left) - you can't go from 1 to 0 coins
# The correct probabilities (0) are already given for the other absorbing state (0 coins left) in the last row of the matrix
m[-2] = m[-2] * 0

# Matrix algebra to find the probability of absorption in each state to each absorption state (1 coin left or 0 coins left)
# I've used this code before here: https://github.com/khgiddon/misc/blob/main/riddler_2020_10_23_notebook.ipynb
# hardcoded 2 for 2 absorbing states
I = np.eye(len(m) - 2)  
Q = m[:-2, :-2]
R = m[:-2,-2:]
absorption_probabilities = np.matmul(np.linalg.inv(I - Q), R)
lucky_prob = absorption_probabilities[0,0]

print(f'the probability of winning is {lucky_prob}')

# the exact probability of finding a lucky coin is 0.7213533784217128

In [ ]:
absorption_probabilities

In [12]:
R

array([[0.00976563, 0.00097656],
       [0.01757813, 0.00195312],
       [0.03125   , 0.00390625],
       [0.0546875 , 0.0078125 ],
       [0.09375   , 0.015625  ],
       [0.15625   , 0.03125   ],
       [0.25      , 0.0625    ],
       [0.375     , 0.125     ],
       [0.5       , 0.25      ]])

In [16]:
np.linalg.inv(I - Q)

array([[1.00097752, 0.0097943 , 0.04433361, 0.12031611, 0.22177955,
        0.30861812, 0.37643891, 0.48155982, 0.71925007],
       [0.        , 1.00195695, 0.01768159, 0.07156172, 0.1729331 ,
        0.28737679, 0.38017241, 0.48766744, 0.719868  ],
       [0.        , 0.        , 1.00392157, 0.03161958, 0.11330348,
        0.24301175, 0.37086066, 0.49407714, 0.72245315],
       [0.        , 0.        , 0.        , 1.00787402, 0.055993  ,
        0.17610702, 0.33731267, 0.49422854, 0.72711879],
       [0.        , 0.        , 0.        , 0.        , 1.01587302,
        0.09831029, 0.2703533 , 0.47516641, 0.7311828 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.03225806, 0.17204301, 0.41781874, 0.7250384 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.06666667, 0.3047619 , 0.68571429],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.14285714, 0.57142857],


In [15]:
np.matmul(np.linalg.inv(I - Q), R)

array([[0.72124566, 0.27875434],
       [0.7210461 , 0.2789539 ],
       [0.7209152 , 0.2790848 ],
       [0.72110744, 0.27889256],
       [0.72196621, 0.27803379],
       [0.7235023 , 0.2764977 ],
       [0.72380952, 0.27619048],
       [0.71428571, 0.28571429],
       [0.66666667, 0.33333333]])

In [17]:
R

array([[0.00976563, 0.00097656],
       [0.01757813, 0.00195312],
       [0.03125   , 0.00390625],
       [0.0546875 , 0.0078125 ],
       [0.09375   , 0.015625  ],
       [0.15625   , 0.03125   ],
       [0.25      , 0.0625    ],
       [0.375     , 0.125     ],
       [0.5       , 0.25      ]])

In [18]:
# https://fivethirtyeight.com/features/can-you-find-the-luckiest-coin/

import numpy as np
from scipy.stats import binom

# There are two absorbing states: when there are 0 coins left (losing) or 1 coin left (winning with a lucky coins)
# We want to construct a transition matrix of each number of coins left to each possible number of coins remaining after flipping
# We can find the exact probabilities using the binomial distribution, and fill out a matrix of transition probability
# We use N=1000 because a 1,000,000  ^ 2 cell transition matrix is too large

max_n = 1000000
m = np.zeros((max_n+1,max_n+1))
p = 0.5
for n in range(1,max_n+1):
    for k in range(0,n+1):
        m[max_n-n,max_n-k] = binom.pmf(k, n, p, loc=0)
        

/Users/kylegiddon/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_discrete_distns.py:67: RuntimeWarning: divide by zero encountered in _binom_pdf
  return _boost._binom_pdf(x, n, p)


KeyboardInterrupt: 

In [ ]:
12:07